CREATE TYPE genotype;

CREATE OR REPLACE FUNCTION genotype_in( CSTRING )
	RETURNS genotype
	AS 'MODULE_PATHNAME'
	LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION genotype_out( genotype )
	RETURNS CSTRING
	AS 'MODULE_PATHNAME'
	LANGUAGE C IMMUTABLE STRICT;

CREATE TYPE genotype (
	INPUT = genotype_in,
	OUTPUT = genotype_out,
	INTERNALLENGTH = 4,
	PASSEDBYVALUE,
	ALIGNMENT = int4
);
